# This file was generated by GoReleaser. DO NOT EDIT.
cask "fdn" do
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Darwin_x86_64.tar.gz"
      sha256 "ca458b0e15ab4d4a3f40e0d14794e0d91ea521b22872d8ad0ec6203a49e3ed23"
    end
    on_arm do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Darwin_arm64.tar.gz"
      sha256 "adaba02e46ec2f15c79f2a8e5c9f790a0e2d35b2a3674d1214caeef190521c1e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Linux_x86_64.tar.gz"
      sha256 "f5f35d2b92be27cb59435a9b7bae0f6a9b83a146613943b60f558c650662f10c"
    end
    on_arm do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Linux_arm64.tar.gz"
      sha256 "0493a003b330ffeeb265987aa8b177ca6b67e669f68f1dbf2ec396bca82b1098"
    end
  end

  name "fdn"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fdn"

  # No zap stanza required

end
