# This file was generated by GoReleaser. DO NOT EDIT.
cask "fdn" do
  name "fdn"
  desc ""
  homepage ""
  version "0.7.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fdn"

  on_macos do
    on_intel do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Darwin_x86_64.tar.gz"
      sha256 "cf61c435f4a28c6f02fd8ac3e81bb728c3960bd323465d217bdcf9953edcb6ff"
    end
    on_arm do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Darwin_arm64.tar.gz"
      sha256 "5d46cfa8e0c907904ca64b3508ceaed0565bbdbb33cd61730b84c672016abc9c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Linux_x86_64.tar.gz"
      sha256 "107b304fb32c43a9c3736565ecd8825ce4b55ca5b4c352b1ac45c28deb85e08b"
    end
    on_arm do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Linux_arm64.tar.gz"
      sha256 "8db847357011876e532638866f9cbacd3cf898e85b8a6672ebc42f8aa298bd6f"
    end
  end

  # No zap stanza required
end
