# This file was generated by GoReleaser. DO NOT EDIT.
cask "fdn" do
  name "fdn"
  desc ""
  homepage ""
  version "0.7.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fdn"

  on_macos do
    on_intel do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Darwin_x86_64.tar.gz"
      sha256 "e0c093d79186a9dd2a77faae67dfb9094aa987608eb9843e3543a3c9afad6463"
    end
    on_arm do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Darwin_arm64.tar.gz"
      sha256 "f26c86724bec1306d6119c731193211afd08993572efba225ee0715e4838a525"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Linux_x86_64.tar.gz"
      sha256 "03be0b6426d2f43b2715e3501e5234ab7885df9daa09783f434d21d6e723dcdf"
    end
    on_arm do
      url "https://github.com/hobbymarks/fdn/releases/download/v#{version}/fdn_Linux_arm64.tar.gz"
      sha256 "c9ea6474041a06ca102d08b0406326753f8e1c7fce89c99cdfc46a2c54e9615e"
    end
  end

  # No zap stanza required
end
