# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fdn < Formula
  desc "File and directory name normalizer with rollback"
  homepage "https://github.com/hobbymarks/fdn"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/fdn/releases/download/v1.1.0/fdn_Darwin_x86_64.tar.gz"
      sha256 "611621251338aea5f3228674556ca95a639f0bedd489a525fec9fd70e8df5110"

      define_method(:install) do
        bin.install "fdn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hobbymarks/fdn/releases/download/v1.1.0/fdn_Darwin_arm64.tar.gz"
      sha256 "57ef5536a42544f050c55907c67d125e927bc71ae658e0520616d6a951a5f9ac"

      define_method(:install) do
        bin.install "fdn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/fdn/releases/download/v1.1.0/fdn_Linux_x86_64.tar.gz"
      sha256 "97fbc85211e69835f32d4e1730f891f9a335ce99e48827c86c1c1c2fb2bb0af9"
      define_method(:install) do
        bin.install "fdn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/fdn/releases/download/v1.1.0/fdn_Linux_arm64.tar.gz"
      sha256 "3c52d6aa0069c843404966099bc281cf10291476a026a2881734074d67b2a6f8"
      define_method(:install) do
        bin.install "fdn"
      end
    end
  end
end
