# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fdn < Formula
  desc "File and directory name normalizer with rollback"
  homepage "https://github.com/hobbymarks/fdn"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/fdn/releases/download/v1.0.4/fdn_Darwin_x86_64.tar.gz"
      sha256 "4fae6799c7bee2648c684cb14aa48a6a9d04f866cb82438e13eeef62091ba254"

      define_method(:install) do
        bin.install "fdn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hobbymarks/fdn/releases/download/v1.0.4/fdn_Darwin_arm64.tar.gz"
      sha256 "087f5f73d6577064d6eb7528a7c9bddb90e1586c8f9b7d86ac69f07065ca87ed"

      define_method(:install) do
        bin.install "fdn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/fdn/releases/download/v1.0.4/fdn_Linux_x86_64.tar.gz"
      sha256 "108f351ab898fab152f69f8fcf5b05752b076221966751394246d1ba84e44c4f"
      define_method(:install) do
        bin.install "fdn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/fdn/releases/download/v1.0.4/fdn_Linux_arm64.tar.gz"
      sha256 "13947a30ea2259d499e721ddf80a70b1a994b5eebdf9cbe438640d3bc0294d80"
      define_method(:install) do
        bin.install "fdn"
      end
    end
  end
end
