# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtr < Formula
  desc "Multi-engine translation CLI inspired by translate-shell"
  homepage "https://github.com/hobbymarks/gtr"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/gtr/releases/download/v0.2.0/gtr_0.2.0_darwin_amd64.tar.gz"
      sha256 "2a15f5344302186021ffb0571789816f579e7ecd0b651cf8a57c22b9058b619c"

      define_method(:install) do
        bin.install "gtr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hobbymarks/gtr/releases/download/v0.2.0/gtr_0.2.0_darwin_arm64.tar.gz"
      sha256 "a44259d55f50b8d739cbb799d827b517933d761e1dc67bcc4efc92084c63338c"

      define_method(:install) do
        bin.install "gtr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/gtr/releases/download/v0.2.0/gtr_0.2.0_linux_amd64.tar.gz"
      sha256 "407bd73b301a850bf5dc3c5b0663dea1d62b9e70e426e36623f5140ddec6f6ac"
      define_method(:install) do
        bin.install "gtr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/gtr/releases/download/v0.2.0/gtr_0.2.0_linux_arm64.tar.gz"
      sha256 "c756a7be0113fb52ebd1e9854633a8fd058b079e554e90dffc8bc4582463d942"
      define_method(:install) do
        bin.install "gtr"
      end
    end
  end
end
