# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gtr < Formula
  desc "Multi-engine translation CLI inspired by translate-shell"
  homepage "https://github.com/hobbymarks/gtr"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hobbymarks/gtr/releases/download/v0.1.4/gtr_0.1.4_darwin_amd64.tar.gz"
      sha256 "3abe106b51d555354329df41f2d362ddc24801aceb3d7442ed41fd1182cbda72"

      define_method(:install) do
        bin.install "gtr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hobbymarks/gtr/releases/download/v0.1.4/gtr_0.1.4_darwin_arm64.tar.gz"
      sha256 "c685f3d6f10fe41f4e28aaf4f2009e3aa4c092e7a09e9c6c13b4e1bea5a80eea"

      define_method(:install) do
        bin.install "gtr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/gtr/releases/download/v0.1.4/gtr_0.1.4_linux_amd64.tar.gz"
      sha256 "de1b31a1f82b2810811658c6987f5a7ee374746111a9f940522e33eaee4d14f5"
      define_method(:install) do
        bin.install "gtr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hobbymarks/gtr/releases/download/v0.1.4/gtr_0.1.4_linux_arm64.tar.gz"
      sha256 "2e05c2bd77b9a9316ea11ff954062f41592778519983576b549fd17a99f3f8a7"
      define_method(:install) do
        bin.install "gtr"
      end
    end
  end
end
